# Generated by Django 4.1.1 on 2022-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fechaDeNac',
            field=models.DateField(),
        ),
    ]
