# Generated by Django 4.1.1 on 2022-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_familiares_fechadenac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fechaDeNac',
            field=models.DateField(),
        ),
    ]
